# Generated by Django 5.1.4 on 2024-12-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Czasomierz_app', '0002_worklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
