# Generated by Django 5.1.4 on 2024-12-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Czasomierz_app', '0003_alter_worklog_end_time_alter_worklog_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
