# Generated by Django 5.1.4 on 2025-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Czasomierz_app', '0004_worklog_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='name',
            field=models.CharField(default='Rejestracja czasu pracy', max_length=100),
        ),
    ]
