# Generated by Django 5.1.4 on 2025-01-09 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Czasomierz_app', '0006_amountofleave_offworklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountofleave',
            name='used_days',
        ),
        migrations.AlterField(
            model_name='offworklog',
            name='status',
            field=models.CharField(choices=[('oczekuje', 'Oczekuje'), ('zaakceptowany', 'Zaakceptowany'), ('odrzucony', 'Odrzucony')], default='oczekuje', max_length=30),
        ),
        migrations.CreateModel(
            name='UsedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_days', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
