# Generated by Django 5.1.4 on 2025-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Czasomierz_app', '0007_remove_amountofleave_used_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofleave',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='offworklog',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
